### ISSUE TITLE
OSError: [Errno 24] Too many open files (with num_parallel 64)

### ISSUE THREAD

**Issue by geohot** [kuterd/nv_isa_solver#2]
WIth `--num_parallel 64`, too much? I have 32 cores in my machine.

```
Traceback (most recent call last):
  File "/home/tiny/build/nv_isa_solver/nv_isa_solver/instruction_solver.py", line 1339, in analyse_operand_interactions
    interaction_data, self.operand_interaction_raw = analyse_live_ranges(
  File "/home/tiny/build/nv_isa_solver/nv_isa_solver/life_range.py", line 153, in analyse_live_ranges
    result = get_live_ranges(tmp.name)
  File "/home/tiny/build/nv_isa_solver/nv_isa_solver/life_range.py", line 123, in get_live_ranges
    proc = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 837, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/usr/lib/python3.10/subprocess.py", line 1643, in _get_handles
    errread, errwrite = os.pipe()
OSError: [Errno 24] Too many open files
```

Less parallel seems okay.

**Comment by geohot** [comment]
Fixed with less parallel

**Comment by kuterd** [comment]
We automatically spawn `nvdisasm` processes based on the number of cores you have. the `--num_parallel` here specifies how many instructions we should solve in parallel. You should probably use something like 3
